include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - lib/l10n/gen/*
    - lib/generated_plugin_registrant.dart
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
  errors:
    invalid_annotation_target: ignore
linter:
  rules:
    public_member_api_docs: false
    one_member_abstracts: ignore


formatter:
  trailing_commas: preserve
