name: PR Preview - GitHub Pages (Flutter Web)

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.32.0"

      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Generate code (optional)
        run: |
          flutter packages run build_runner build --delete-conflicting-outputs || true

      - name: Analyze
        run: flutter analyze lib

      - name: Build web
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          flutter build web --target lib/main_production.dart --release --base-href "/${REPO_NAME}/pr-${{ github.event.number }}/"

      - name: Deploy to gh-pages/pr-<num>
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          destination_dir: pr-${{ github.event.number }}
          keep_files: true

      - name: Comment preview URL
        uses: actions/github-script@v7
        with:
          script: |
            const repo = context.payload.repository.name;
            const owner = context.payload.repository.owner.login;
            const pr = context.payload.number;
            const url = `https://${owner}.github.io/${repo}/pr-${pr}/`;
            const body = `🧪 PR Preview available:\n\n${url}`;
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: pr,
              body,
            });

  cleanup-preview:
    if: ${{ github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Remove PR preview directory
        run: |
          rm -rf pr-${{ github.event.number }} || true

      - name: Push cleanup
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          git commit -m "chore: remove PR preview pr-${{ github.event.number }}" || echo "No changes"
          git push

