name: Release GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.32.5"

      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Format
        run: dart format --set-exit-if-changed lib test

      - name: Generate code
        run: |
          flutter packages run build_runner build --delete-conflicting-outputs

      - name: Analyze
        run: flutter analyze lib

      - name: Build web (production)
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          flutter build web --target lib/main_production.dart --release \
            --dart-define=URL_SCHEME=${{ vars.URL_SCHEME }} \
            --dart-define=BASE_DOMAIN=${{ vars.BASE_DOMAIN }} \
            --dart-define=API_KEY=${{ secrets.API_KEY }} \
            --base-href "/${REPO_NAME}/"

      - name: Deploy to gh-pages (root)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web

